/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerificationNumeroRouteImport } from './routes/verification.$numero'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'
import { Route as AuthenticatedGenererRouteImport } from './routes/_authenticated/generer'
import { Route as AuthenticatedFormationsRouteImport } from './routes/_authenticated/formations'
import { Route as AuthenticatedExpirationsRouteImport } from './routes/_authenticated/expirations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents.index'
import { Route as AuthenticatedApprenantsIndexRouteImport } from './routes/_authenticated/apprenants.index'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as AuthenticatedApprenantsNouveauRouteImport } from './routes/_authenticated/apprenants.nouveau'
import { Route as AuthenticatedApprenantsIdRouteImport } from './routes/_authenticated/apprenants.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationNumeroRoute = VerificationNumeroRouteImport.update({
  id: '/verification/$numero',
  path: '/verification/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGenererRoute = AuthenticatedGenererRouteImport.update({
  id: '/generer',
  path: '/generer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormationsRoute = AuthenticatedFormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpirationsRoute =
  AuthenticatedExpirationsRouteImport.update({
    id: '/expirations',
    path: '/expirations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApprenantsIndexRoute =
  AuthenticatedApprenantsIndexRouteImport.update({
    id: '/apprenants/',
    path: '/apprenants/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApprenantsNouveauRoute =
  AuthenticatedApprenantsNouveauRouteImport.update({
    id: '/apprenants/nouveau',
    path: '/apprenants/nouveau',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApprenantsIdRoute =
  AuthenticatedApprenantsIdRouteImport.update({
    id: '/apprenants/$id',
    path: '/apprenants/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expirations': typeof AuthenticatedExpirationsRoute
  '/formations': typeof AuthenticatedFormationsRoute
  '/generer': typeof AuthenticatedGenererRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/import': typeof AuthenticatedImportRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/verification/$numero': typeof VerificationNumeroRoute
  '/apprenants/$id': typeof AuthenticatedApprenantsIdRoute
  '/apprenants/nouveau': typeof AuthenticatedApprenantsNouveauRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/apprenants/': typeof AuthenticatedApprenantsIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expirations': typeof AuthenticatedExpirationsRoute
  '/formations': typeof AuthenticatedFormationsRoute
  '/generer': typeof AuthenticatedGenererRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/import': typeof AuthenticatedImportRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/verification/$numero': typeof VerificationNumeroRoute
  '/apprenants/$id': typeof AuthenticatedApprenantsIdRoute
  '/apprenants/nouveau': typeof AuthenticatedApprenantsNouveauRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/apprenants': typeof AuthenticatedApprenantsIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expirations': typeof AuthenticatedExpirationsRoute
  '/_authenticated/formations': typeof AuthenticatedFormationsRoute
  '/_authenticated/generer': typeof AuthenticatedGenererRoute
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/verification/$numero': typeof VerificationNumeroRoute
  '/_authenticated/apprenants/$id': typeof AuthenticatedApprenantsIdRoute
  '/_authenticated/apprenants/nouveau': typeof AuthenticatedApprenantsNouveauRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/apprenants/': typeof AuthenticatedApprenantsIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/expirations'
    | '/formations'
    | '/generer'
    | '/historique'
    | '/import'
    | '/parametres'
    | '/verification/$numero'
    | '/apprenants/$id'
    | '/apprenants/nouveau'
    | '/documents/$id'
    | '/apprenants/'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/expirations'
    | '/formations'
    | '/generer'
    | '/historique'
    | '/import'
    | '/parametres'
    | '/verification/$numero'
    | '/apprenants/$id'
    | '/apprenants/nouveau'
    | '/documents/$id'
    | '/apprenants'
    | '/documents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/expirations'
    | '/_authenticated/formations'
    | '/_authenticated/generer'
    | '/_authenticated/historique'
    | '/_authenticated/import'
    | '/_authenticated/parametres'
    | '/verification/$numero'
    | '/_authenticated/apprenants/$id'
    | '/_authenticated/apprenants/nouveau'
    | '/_authenticated/documents/$id'
    | '/_authenticated/apprenants/'
    | '/_authenticated/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerificationNumeroRoute: typeof VerificationNumeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification/$numero': {
      id: '/verification/$numero'
      path: '/verification/$numero'
      fullPath: '/verification/$numero'
      preLoaderRoute: typeof VerificationNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/generer': {
      id: '/_authenticated/generer'
      path: '/generer'
      fullPath: '/generer'
      preLoaderRoute: typeof AuthenticatedGenererRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formations': {
      id: '/_authenticated/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof AuthenticatedFormationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expirations': {
      id: '/_authenticated/expirations'
      path: '/expirations'
      fullPath: '/expirations'
      preLoaderRoute: typeof AuthenticatedExpirationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apprenants/': {
      id: '/_authenticated/apprenants/'
      path: '/apprenants'
      fullPath: '/apprenants/'
      preLoaderRoute: typeof AuthenticatedApprenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apprenants/nouveau': {
      id: '/_authenticated/apprenants/nouveau'
      path: '/apprenants/nouveau'
      fullPath: '/apprenants/nouveau'
      preLoaderRoute: typeof AuthenticatedApprenantsNouveauRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apprenants/$id': {
      id: '/_authenticated/apprenants/$id'
      path: '/apprenants/$id'
      fullPath: '/apprenants/$id'
      preLoaderRoute: typeof AuthenticatedApprenantsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpirationsRoute: typeof AuthenticatedExpirationsRoute
  AuthenticatedFormationsRoute: typeof AuthenticatedFormationsRoute
  AuthenticatedGenererRoute: typeof AuthenticatedGenererRoute
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedApprenantsIdRoute: typeof AuthenticatedApprenantsIdRoute
  AuthenticatedApprenantsNouveauRoute: typeof AuthenticatedApprenantsNouveauRoute
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
  AuthenticatedApprenantsIndexRoute: typeof AuthenticatedApprenantsIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpirationsRoute: AuthenticatedExpirationsRoute,
  AuthenticatedFormationsRoute: AuthenticatedFormationsRoute,
  AuthenticatedGenererRoute: AuthenticatedGenererRoute,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedApprenantsIdRoute: AuthenticatedApprenantsIdRoute,
  AuthenticatedApprenantsNouveauRoute: AuthenticatedApprenantsNouveauRoute,
  AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  AuthenticatedApprenantsIndexRoute: AuthenticatedApprenantsIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  VerificationNumeroRoute: VerificationNumeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
